import { DESIGN_SYSTEM_TOKENS, PLATFORM_NAME, PLATFORM_POLICY, PLATFORM_RUNTIME, PLATFORM_VERSION, SOURCE_OF_TRUTH } from "./platform";

export { DESIGN_SYSTEM_TOKENS, PLATFORM_NAME, PLATFORM_POLICY, PLATFORM_RUNTIME, PLATFORM_VERSION, SOURCE_OF_TRUTH };

export const COOKIE_NAME = PLATFORM_POLICY.sessionCookieName;
export const ONE_YEAR_MS = 365 * 24 * 60 * 60 * 1000;
export const AXIOS_TIMEOUT_MS = 15_000;
export const UNAUTHED_ERR_MSG = PLATFORM_POLICY.authRequiredMessage;
export const NOT_ADMIN_ERR_MSG = PLATFORM_POLICY.adminRequiredMessage;
